const systemSizeMW = 1.0;
const durationHours = 4;
const totalEnergyKWh = systemSizeMW * durationHours * 1000;
const batteryCostPerKWh = 175;
const battery = totalEnergyKWh * batteryCostPerKWh;
const inverter = systemSizeMW * 1000 * 120;
const xfmrPerKVA = 80 * 0.85;
const xfmrMVA = Math.max(0.1, Math.ceil(systemSizeMW * 1.25 * 10) / 10);
const transformer = xfmrMVA * 1000 * xfmrPerKVA;
const switchgear = systemSizeMW * 1000 * 50 * 0.6;
const bms = battery * 0.05;
const enclosure = battery * 0.08;
const monitoring = battery * 0.02;
const equipTotal = battery + inverter + transformer + switchgear + bms + enclosure + monitoring;

console.log("=== CORRECTED (1 MW / 4h) ===");
console.log("Battery: $" + battery.toLocaleString());
console.log("Inverter: $" + inverter.toLocaleString());
console.log("Transformer: $" + transformer.toLocaleString());
console.log("Switchgear: $" + switchgear.toLocaleString());
console.log("BMS: $" + bms.toLocaleString());
console.log("Enclosure: $" + enclosure.toLocaleString());
console.log("Monitoring: $" + monitoring.toLocaleString());
console.log("TOTAL: $" + equipTotal.toLocaleString());
console.log("$/kWh: $" + (equipTotal / totalEnergyKWh).toFixed(0));

console.log("");
console.log("=== BEFORE FIX ===");
var pcsCost = systemSizeMW * 1000 * 120;
var bosCost = systemSizeMW * 1000 * 28.8;
var epcCost = systemSizeMW * 1000 * 36;
var oldCostPerKWh = (battery + pcsCost + bosCost + epcCost) / totalEnergyKWh;
var oldBattery = totalEnergyKWh * oldCostPerKWh;
var oldTotal = oldBattery + inverter + transformer + switchgear + oldBattery*0.05 + oldBattery*0.08 + oldBattery*0.02;
console.log("Old costPerKWh used: $" + oldCostPerKWh.toFixed(0));
console.log("Old battery line: $" + oldBattery.toLocaleString());
console.log("Old TOTAL: $" + oldTotal.toLocaleString());
console.log("Old $/kWh: $" + (oldTotal / totalEnergyKWh).toFixed(0));
