/**
 * CALCULATOR REGISTRY — THIN INDEX
 * =================================
 * Op2 refactor: Each industry calculator lives in industries/<name>.ts
 * This file is the public API: imports all adapters and builds the lookup map.
 *
 * To add a new industry:
 *   1. Create src/wizard/v7/calculators/industries/<name>.ts
 *   2. Export the CalculatorContract constant
 *   3. Import below and register in CALCULATORS_BY_ID
 */

import type { CalculatorContract } from "./contract";

import {
  GENERIC_SSOT_ADAPTER,
  DC_LOAD_V1_SSOT,
  HOTEL_LOAD_V1_SSOT,
  CAR_WASH_LOAD_V1_SSOT,
  OFFICE_LOAD_V1_SSOT,
  RETAIL_LOAD_V1_SSOT,
  MANUFACTURING_LOAD_V1_SSOT,
  HOSPITAL_LOAD_V1_SSOT,
  WAREHOUSE_LOAD_V1_SSOT,
  EV_CHARGING_LOAD_V1_SSOT,
  RESTAURANT_LOAD_V1_SSOT,
  TRUCK_STOP_LOAD_V1_SSOT,
  GAS_STATION_LOAD_V1_SSOT,
  AIRPORT_LOAD_V1_SSOT,
  CASINO_LOAD_V1_SSOT,
  APARTMENT_LOAD_V1_SSOT,
  COLLEGE_LOAD_V1_SSOT,
  COLD_STORAGE_LOAD_V1_SSOT,
  INDOOR_FARM_LOAD_V1_SSOT,
  AGRICULTURE_LOAD_V1_SSOT,
  RESIDENTIAL_LOAD_V1_SSOT,
  GOVERNMENT_LOAD_V1_SSOT,
  SHOPPING_CENTER_LOAD_V1_SSOT,
  MICROGRID_LOAD_V1_SSOT,
} from "./industries";

// Re-export all adapters so external consumers keep the same import paths
export {
  GENERIC_SSOT_ADAPTER,
  DC_LOAD_V1_SSOT,
  HOTEL_LOAD_V1_SSOT,
  CAR_WASH_LOAD_V1_SSOT,
  OFFICE_LOAD_V1_SSOT,
  RETAIL_LOAD_V1_SSOT,
  MANUFACTURING_LOAD_V1_SSOT,
  HOSPITAL_LOAD_V1_SSOT,
  WAREHOUSE_LOAD_V1_SSOT,
  EV_CHARGING_LOAD_V1_SSOT,
  RESTAURANT_LOAD_V1_SSOT,
  TRUCK_STOP_LOAD_V1_SSOT,
  GAS_STATION_LOAD_V1_SSOT,
  AIRPORT_LOAD_V1_SSOT,
  CASINO_LOAD_V1_SSOT,
  APARTMENT_LOAD_V1_SSOT,
  COLLEGE_LOAD_V1_SSOT,
  COLD_STORAGE_LOAD_V1_SSOT,
  INDOOR_FARM_LOAD_V1_SSOT,
  AGRICULTURE_LOAD_V1_SSOT,
  RESIDENTIAL_LOAD_V1_SSOT,
  GOVERNMENT_LOAD_V1_SSOT,
  SHOPPING_CENTER_LOAD_V1_SSOT,
  MICROGRID_LOAD_V1_SSOT,
};

// ── Lookup map ─────────────────────────────────────────────────────────────
export const CALCULATORS_BY_ID: Record<string, CalculatorContract> = {
  [GENERIC_SSOT_ADAPTER.id]: GENERIC_SSOT_ADAPTER,
  [DC_LOAD_V1_SSOT.id]: DC_LOAD_V1_SSOT,
  [HOTEL_LOAD_V1_SSOT.id]: HOTEL_LOAD_V1_SSOT,
  [CAR_WASH_LOAD_V1_SSOT.id]: CAR_WASH_LOAD_V1_SSOT,
  [OFFICE_LOAD_V1_SSOT.id]: OFFICE_LOAD_V1_SSOT,
  [RETAIL_LOAD_V1_SSOT.id]: RETAIL_LOAD_V1_SSOT,
  [MANUFACTURING_LOAD_V1_SSOT.id]: MANUFACTURING_LOAD_V1_SSOT,
  [HOSPITAL_LOAD_V1_SSOT.id]: HOSPITAL_LOAD_V1_SSOT,
  [WAREHOUSE_LOAD_V1_SSOT.id]: WAREHOUSE_LOAD_V1_SSOT,
  [EV_CHARGING_LOAD_V1_SSOT.id]: EV_CHARGING_LOAD_V1_SSOT,
  [RESTAURANT_LOAD_V1_SSOT.id]: RESTAURANT_LOAD_V1_SSOT,
  [TRUCK_STOP_LOAD_V1_SSOT.id]: TRUCK_STOP_LOAD_V1_SSOT,
  [GAS_STATION_LOAD_V1_SSOT.id]: GAS_STATION_LOAD_V1_SSOT,
  [AIRPORT_LOAD_V1_SSOT.id]: AIRPORT_LOAD_V1_SSOT,
  [CASINO_LOAD_V1_SSOT.id]: CASINO_LOAD_V1_SSOT,
  [APARTMENT_LOAD_V1_SSOT.id]: APARTMENT_LOAD_V1_SSOT,
  [COLLEGE_LOAD_V1_SSOT.id]: COLLEGE_LOAD_V1_SSOT,
  [COLD_STORAGE_LOAD_V1_SSOT.id]: COLD_STORAGE_LOAD_V1_SSOT,
  [INDOOR_FARM_LOAD_V1_SSOT.id]: INDOOR_FARM_LOAD_V1_SSOT,
  [AGRICULTURE_LOAD_V1_SSOT.id]: AGRICULTURE_LOAD_V1_SSOT,
  [RESIDENTIAL_LOAD_V1_SSOT.id]: RESIDENTIAL_LOAD_V1_SSOT,
  [GOVERNMENT_LOAD_V1_SSOT.id]: GOVERNMENT_LOAD_V1_SSOT,
  [SHOPPING_CENTER_LOAD_V1_SSOT.id]: SHOPPING_CENTER_LOAD_V1_SSOT,
  [MICROGRID_LOAD_V1_SSOT.id]: MICROGRID_LOAD_V1_SSOT,
};

// ── Utility helpers ────────────────────────────────────────────────────────

/**
 * Get calculator contract by ID.
 * @param id - Calculator ID (e.g. "dc_load_v1")
 */
export function getCalculator(id: string): CalculatorContract | undefined {
  return CALCULATORS_BY_ID[id];
}

/**
 * List all registered calculator IDs.
 * Useful for admin panels, debugging, and template validation.
 */
export function listCalculatorIds(): string[] {
  return Object.keys(CALCULATORS_BY_ID);
}
