#!/bin/bash

# SmartWizard Performance Test Runner
# ====================================
# Runs all performance tests and generates comprehensive report

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     SMARTWIZARD COMPREHENSIVE PERFORMANCE TEST SUITE       ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Create results directory
RESULTS_DIR="./test-results/performance-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$RESULTS_DIR"

echo "📁 Results will be saved to: $RESULTS_DIR"
echo ""

# Function to run test and save results
run_test() {
  local test_name=$1
  local test_file=$2
  local output_file="$RESULTS_DIR/${test_name}.log"
  
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "Running: $test_name"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  
  npx ts-node "$test_file" 2>&1 | tee "$output_file"
  
  if [ ${PIPESTATUS[0]} -eq 0 ]; then
    echo -e "${GREEN}✅ $test_name PASSED${NC}"
  else
    echo -e "${RED}❌ $test_name FAILED${NC}"
  fi
  echo ""
}

# Test 1: Main Performance Suite
run_test "wizard-performance" "tests/performance/wizard-performance-test.ts"

# Test 2: Database Queries
run_test "database-queries" "tests/performance/database-query-test.ts"

# Test 3: Calculation Benchmarks
run_test "calculation-benchmarks" "tests/performance/calculation-benchmark.ts"

# Generate Summary Report
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 GENERATING SUMMARY REPORT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

SUMMARY_FILE="$RESULTS_DIR/SUMMARY.md"

cat > "$SUMMARY_FILE" << EOF
# Performance Test Summary
**Date**: $(date)

## Test Results

### Wizard Performance Test
\`\`\`
$(cat "$RESULTS_DIR/wizard-performance.log")
\`\`\`

### Database Query Test
\`\`\`
$(cat "$RESULTS_DIR/database-queries.log")
\`\`\`

### Calculation Benchmark
\`\`\`
$(cat "$RESULTS_DIR/calculation-benchmarks.log")
\`\`\`

## Bottlenecks Identified

### Critical (>500ms)
$(grep "🔴\|❌" "$RESULTS_DIR"/*.log | grep -v "Test suite" || echo "None found")

### Warnings (>200ms)
$(grep "🟡\|⚠️" "$RESULTS_DIR"/*.log || echo "None found")

## Recommendations

1. Review all CRITICAL bottlenecks immediately
2. Optimize SLOW queries and calculations
3. Consider implementing additional caching
4. Monitor memory usage patterns

---
Generated by SmartWizard Performance Test Suite
EOF

echo "✅ Summary report saved to: $SUMMARY_FILE"
echo ""

# Open summary in default viewer
if command -v open &> /dev/null; then
  echo "📖 Opening summary report..."
  open "$SUMMARY_FILE"
elif command -v xdg-open &> /dev/null; then
  xdg-open "$SUMMARY_FILE"
fi

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║              PERFORMANCE TESTING COMPLETE                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📁 All results saved to: $RESULTS_DIR"
